# Generated by Django 4.0.3 on 2022-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_label', models.CharField(max_length=20, verbose_name='Enter datafile label')),
                ('db_date', models.DateField(default='2022-06-07', verbose_name='Enter date in format YYYY-MM-DD')),
                ('db_path', models.FileField(upload_to='password_files', verbose_name='".json" file')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(help_text='Enter card name', max_length=50, verbose_name='My Card name')),
                ('card_number', models.SlugField(help_text='Enter card name', max_length=16, verbose_name='Card number')),
                ('card_validity', models.CharField(help_text='Enter card name', max_length=5, verbose_name='Valid thru')),
                ('card_holder', models.CharField(help_text="Enter cardholder's name", max_length=50, verbose_name='Cardholder')),
                ('card_cvv', models.SlugField(help_text='Enter CVV', max_length=3, verbose_name='CVV')),
                ('card_pin', models.SlugField(help_text='Enter PIN code', max_length=4, verbose_name='PIN code')),
                ('card_note', models.CharField(blank=True, help_text='Enter note about card', max_length=200, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Enter account name', max_length=50, verbose_name='My account')),
                ('account_url', models.URLField(help_text='Enter URL', max_length=150, verbose_name='URL')),
                ('account_login', models.CharField(help_text='Enter log name', max_length=50, verbose_name='Log name')),
                ('account_password', models.CharField(help_text='Enter password', max_length=50, verbose_name='Password')),
                ('account_note', models.CharField(blank=True, help_text='Enter note about card', max_length=200, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_label', models.CharField(help_text="Enter note's label", max_length=50, verbose_name='My note')),
                ('note_text', models.CharField(blank=True, help_text="Enter note's text", max_length=300, null=True, verbose_name='Note')),
            ],
        ),
    ]
